version: '3.7'
services:
  dicecloud-db:
    container_name: dicecloud-db
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
      - --replSet=rs0
    volumes:
      - ./dicecloud/data/db:/data/db
  dicecloud:
    container_name: dicecloud
    build:
      context: ./
    environment:
      - ROOT_URL=http://mediaroom.lan:4000
      - MONGO_URL=mongodb://dicecloud-db:27017/test?replicaSet=rs0
      - MONGO_OPLOG_URL=mongodb://dicecloud-db:27017/local?replicaSet=rs0
      - PORT=3000
      - NODE_ENV=production
      - METEOR_SETTINGS={"public":{"environment":"production","disablePatreon":true}}
      - DEFAULT_LIBRARIES=dslPyPFcULEH4kKOE,wAb7GUFHJpzINOjvU
      - CONTAINER_VERSION=2026-03-07
      - MAIL_URL=smtp://EMAIL:PASSWORD@SERVER:PORT
    ports:
      - '4000:3000'
